backend:
  name: git-gateway
  branch: master

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "bridges"
    label: "Bridges"
    folder: "src/bridges"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Bridge Model", name: "bridge_model", widget: "string" }
      - { label: "Use Case", name: "use_case", widget: "string" }
      - { label: "Install Type", name: "install_type", widget: "string" }
      - { label: "Specs Summary", name: "specs_summary", widget: "text" }
      - { label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown" }
      - { label: "CTA Text", name: "cta_text", widget: "string" }
      - { label: "CTA URL", name: "cta_url", widget: "string" }

  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Footer Short Description", name: "shortDesc", widget: "string"}
